import { chromium } from "playwright";
const OUT = process.argv[2];
const URL = "http://localhost:3002/slice-preview/hero/split";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
const page = await ctx.newPage();
await page.goto(URL, { waitUntil: "networkidle", timeout: 90000 });
const t = page.locator('[data-testid="preview-target"]');
await t.waitFor({ state: "visible", timeout: 90000 });
await t.screenshot({ path: OUT });
console.log("✓ screenshot →", OUT);
await browser.close();
