// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Side documents
 */
interface PageDocumentData {
  /**
   * Forældre side field in *Side*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent_page: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Side*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * SEO titel field in *Side*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Vises i Google og i browser-fanen
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * SEO beskrivelse field in *Side*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Den lille tekst der vises under linket i Google
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Billede (Sociale Medier) field in *Side*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Side document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Indstillinger → Viderestillinger*
 */
export interface SettingsDocumentDataRedirectsItem {
  /**
   * Fra URL field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: f.eks. /sommer
   * - **API ID Path**: settings.redirects[].from_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  from_url: prismic.KeyTextField;

  /**
   * Til URL field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: f.eks. /tilbud
   * - **API ID Path**: settings.redirects[].to_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  to_url: prismic.KeyTextField;

  /**
   * Hvorfor laver du dette link? field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 301 (Siden er slettet/flyttet for altid)
   * - **API ID Path**: settings.redirects[].redirect_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  redirect_type: prismic.SelectField<
    | "301 (Siden er slettet/flyttet for altid)"
    | "307 (Dette er blot en midlertidig genvej)",
    "filled"
  >;
}

/**
 * Content for Indstillinger documents
 */
interface SettingsDocumentData {
  /**
   * Tving sprog i URL? (fx /da-dk) field in *Indstillinger*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.force_lang_prefix
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  force_lang_prefix: prismic.BooleanField;

  /**
   * Viderestillinger field in *Indstillinger*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.redirects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redirects: prismic.GroupField<Simplify<SettingsDocumentDataRedirectsItem>>;

  /**
   * Lys farve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_light
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_light: prismic.ColorField;

  /**
   * Mørk farve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_dark
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_dark: prismic.ColorField;

  /**
   * Primær brandfarve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_primary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_primary: prismic.ColorField;

  /**
   * Sekundær brandfarve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_secondary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_secondary: prismic.ColorField;

  /**
   * Layoutbredde field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Bredden på dit hjemmesideindhold
   * - **API ID Path**: settings.layout_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout_width: prismic.SelectField<
    | "Klassisk (1200px)"
    | "Standard (1280px)"
    | "Moderne (1440px)"
    | "Ekspansiv (1664px)"
    | "Cinematic (1920px)"
  >;

  /**
   * Hjørner / radius field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Hvor skape eller bløde kanterne skal være på fx kasser og billeder
   * - **API ID Path**: settings.border_radius
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  border_radius: prismic.SelectField<
    | "Skarpe hjørner (0px)"
    | "Lille afrunding (4px)"
    | "Standard (8px)"
    | "Blød (16px)"
    | "Pilleformet (Fuld radius)"
  >;

  /**
   * Skrifttype (Anbefalet - Hurtig) field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vælg en optimeret skrifttype
   * - **Default Value**: Inter
   * - **API ID Path**: settings.font_select
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  font_select: prismic.SelectField<
    | "Inter"
    | "Montserrat"
    | "Rethink Sans"
    | "Comfortaa"
    | "Poppins"
    | "Abel"
    | "Roboto"
    | "Open Sans",
    "filled"
  >;

  /**
   * Avanceret skrifttype (Bunny Fonts) field in *Indstillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Navn fra fonts.bunny.net (f.eks. "Playfair Display"). Dette felt overstyrer valget ovenfor.
   * - **API ID Path**: settings.custom_font_input
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  custom_font_input: prismic.KeyTextField;
}

/**
 * Indstillinger document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataRedirectsItem,
      AllDocumentTypes,
    };
  }
}
