// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Business → Sociale profiler (sameAs)*
 */
export interface BusinessDocumentDataSocialProfilesItem {
  /**
   * Platform field in *Business → Sociale profiler (sameAs)*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vælg medie...
   * - **API ID Path**: business.social_profiles[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "LinkedIn" | "Facebook" | "Instagram" | "YouTube" | "X" | "Wikipedia"
  >;

  /**
   * Profil URL field in *Business → Sociale profiler (sameAs)*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://linkedin.com/company/dit-brand
   * - **API ID Path**: business.social_profiles[].profile_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  profile_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Business documents
 */
interface BusinessDocumentData {
  /**
   * Virksomhedstype field in *Business*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vælg type...
   * - **API ID Path**: business.schema_type
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  schema_type: prismic.SelectField<
    "Organization" | "LocalBusiness" | "Person" | "Corporation"
  >;

  /**
   * Juridisk navn field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Skal matche evt. CVR
   * - **API ID Path**: business.legal_name
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  legal_name: prismic.KeyTextField;

  /**
   * Alternativt navn field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: F.eks. forkortelse
   * - **API ID Path**: business.alternate_name
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alternate_name: prismic.KeyTextField;

  /**
   * CVR Nummer field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: F.eks. 12345678
   * - **API ID Path**: business.vat_id
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vat_id: prismic.KeyTextField;

  /**
   * Logo (Min. 112x112px, hvid bg) field in *Business*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: business.brand_logo
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logo: prismic.ImageField<never>;

  /**
   * Kort beskrivelse field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: En ultrakort, faktuel beskrivelse af virksomheden...
   * - **API ID Path**: business.description
   * - **Tab**: Stamdata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField; /**
   * Global email field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: F.eks. kontakt@virksomhed.dk
   * - **API ID Path**: business.contact_email
   * - **Tab**: Kontakt & social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Global telefon field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: F.eks. +45 12 34 56 78
   * - **API ID Path**: business.global_telephone
   * - **Tab**: Kontakt & social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  global_telephone: prismic.KeyTextField;

  /**
   * Sociale profiler (sameAs) field in *Business*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: business.social_profiles[]
   * - **Tab**: Kontakt & social
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_profiles: prismic.GroupField<
    Simplify<BusinessDocumentDataSocialProfilesItem>
  >; /**
   * Schema mode (Kill Switch) field in *Business*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Auto (Virksomhed + Brødkrummer)
   * - **API ID Path**: business.schema_mode
   * - **Tab**: Avanceret SEO
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  schema_mode: prismic.SelectField<
    | "Auto (Virksomhed + Brødkrummer)"
    | "Kun brødkrummer"
    | "Deaktiver alt (kun Custom JSON)",
    "filled"
  >;

  /**
   * Custom JSON-LD (Power User) field in *Business*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Indsæt valid JSON-LD kode her. Brug kun hvis du ved, hvad du laver!
   * - **API ID Path**: business.custom_schema_json
   * - **Tab**: Avanceret SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  custom_schema_json: prismic.KeyTextField;
}

/**
 * Business document from Prismic
 *
 * - **API ID**: `business`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BusinessDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BusinessDocumentData>,
    "business",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Side documents
 */
interface PageDocumentData {
  /**
   * Forældre side field in *Side*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent_page: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Side*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * SEO titel field in *Side*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Vises i Google og i browser-fanen
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * SEO beskrivelse field in *Side*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Den lille tekst der vises under linket i Google
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Billede (Sociale Medier) field in *Side*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Side document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Indstillinger → Viderestillinger*
 */
export interface SettingsDocumentDataRedirectsItem {
  /**
   * Fra URL field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: f.eks. /sommer
   * - **API ID Path**: settings.redirects[].from_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  from_url: prismic.KeyTextField;

  /**
   * Til URL field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: f.eks. /tilbud
   * - **API ID Path**: settings.redirects[].to_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  to_url: prismic.KeyTextField;

  /**
   * Hvorfor laver du dette link? field in *Indstillinger → Viderestillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 301 (siden er slettet/flyttet for altid)
   * - **API ID Path**: settings.redirects[].redirect_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  redirect_type: prismic.SelectField<
    | "301 (siden er slettet/flyttet for altid)"
    | "307 (dette er blot en midlertidig genvej)",
    "filled"
  >;
}

/**
 * Content for Indstillinger documents
 */
interface SettingsDocumentData {
  /**
   * Sidenavn field in *Indstillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: F.eks. Jensen Frisør
   * - **API ID Path**: settings.site_name
   * - **Tab**: Generelt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Tving sprog i URL? (fx /da-dk) field in *Indstillinger*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.force_lang_prefix
   * - **Tab**: Generelt
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  force_lang_prefix: prismic.BooleanField; /**
   * Lys farve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_light
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_light: prismic.ColorField;

  /**
   * Mørk farve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_dark
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_dark: prismic.ColorField;

  /**
   * Primær brandfarve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_primary
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_primary: prismic.ColorField;

  /**
   * Sekundær brandfarve field in *Indstillinger*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.color_secondary
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color_secondary: prismic.ColorField;

  /**
   * Layoutbredde field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Bredden på dit hjemmesideindhold
   * - **API ID Path**: settings.layout_width
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout_width: prismic.SelectField<
    | "Klassisk (1200px)"
    | "Standard (1280px)"
    | "Moderne (1440px)"
    | "Ekspansiv (1664px)"
    | "Cinematic (1920px)"
  >;

  /**
   * Hjørner / radius field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Hvor skarpe eller bløde kanterne skal være på fx kasser og billeder
   * - **API ID Path**: settings.border_radius
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  border_radius: prismic.SelectField<
    | "Skarpe hjørner (0px)"
    | "Lille afrunding (4px)"
    | "Standard (8px)"
    | "Blød (16px)"
    | "Pilleformet (fuld radius)"
  >;

  /**
   * Skrifttype (anbefalet - hurtig) field in *Indstillinger*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Vælg en optimeret skrifttype
   * - **Default Value**: System standard
   * - **API ID Path**: settings.font_select
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  font_select: prismic.SelectField<
    | "System standard"
    | "Montserrat"
    | "Rethink Sans"
    | "Comfortaa"
    | "Poppins"
    | "Abel"
    | "Roboto"
    | "Open Sans"
    | "Inter",
    "filled"
  >;

  /**
   * Avanceret skrifttype (Bunny Fonts) field in *Indstillinger*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Navn fra fonts.bunny.net (f.eks. "Playfair Display"). Dette felt overstyrer valget ovenfor.
   * - **API ID Path**: settings.custom_font_input
   * - **Tab**: Udseende og layout
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  custom_font_input: prismic.KeyTextField; /**
   * Viderestillinger field in *Indstillinger*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.redirects[]
   * - **Tab**: Viderestillinger
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redirects: prismic.GroupField<Simplify<SettingsDocumentDataRedirectsItem>>;
}

/**
 * Indstillinger document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BusinessDocument
  | PageDocument
  | SettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BusinessDocument,
      BusinessDocumentData,
      BusinessDocumentDataSocialProfilesItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataRedirectsItem,
      AllDocumentTypes,
    };
  }
}
