// Code generated by Prismic. DO NOT EDIT.

import Faq from "./Faq";
import Features from "./Features";
import FooterColumnLinks from "./FooterColumnLinks";
import FooterColumnText from "./FooterColumnText";
import HeaderClassic from "./HeaderClassic";
import Hero from "./Hero";
import Highlights from "./Highlights";
import PhoneMockup from "./PhoneMockup";
import Testimonials from "./Testimonials";
import TextWithImages from "./TextWithImages";

export const components = {
	faq: Faq,
	features: Features,
	footer_column_links: FooterColumnLinks,
	footer_column_text: FooterColumnText,
	header_classic: HeaderClassic,
	hero: Hero,
	highlights: Highlights,
	phone_mockup: PhoneMockup,
	testimonials: Testimonials,
	text_with_images: TextWithImages
};