// Code generated by Prismic. DO NOT EDIT.

import FooterColumnLinks from "./FooterColumnLinks";
import FooterColumnText from "./FooterColumnText";
import HeaderClassic from "./HeaderClassic";
import Hero from "./Hero";
import SectionFaq from "./SectionFaq";
import SectionFeatures from "./SectionFeatures";
import SectionHighlights from "./SectionHighlights";
import SectionPhoneMockup from "./SectionPhoneMockup";

export const components = {
	footer_column_links: FooterColumnLinks,
	footer_column_text: FooterColumnText,
	header_classic: HeaderClassic,
	hero: Hero,
	section_faq: SectionFaq,
	section_features: SectionFeatures,
	section_highlights: SectionHighlights,
	section_phone_mockup: SectionPhoneMockup
};