// Code generated by Prismic. DO NOT EDIT.

import Faq from "./Faq";
import Features from "./Features";
import FooterColumnLinks from "./FooterColumnLinks";
import FooterColumnText from "./FooterColumnText";
import HeaderClassic from "./HeaderClassic";
import Hero from "./Hero";
import Highlights from "./Highlights";
import PhoneMockup from "./PhoneMockup";

export const components = {
	faq: Faq,
	features: Features,
	footer_column_links: FooterColumnLinks,
	footer_column_text: FooterColumnText,
	header_classic: HeaderClassic,
	hero: Hero,
	highlights: Highlights,
	phone_mockup: PhoneMockup
};